const plants = [
    { plantName: 'Snake Plant (Sansevieria trifasciata)', description: 'It is a stemless evergreen perennial that, with proper care, will last for many years. In its native habitat, plant foliage may rise to as much as 4 feet tall, but is often smaller on indoor plants. Erect, fleshy, sharply-pointed, sword-shaped leaves are deep green with light gray-green horizontal stripes.', image: '', careLevel: 'Beginner', waterLevel: 'infrequent watering', lightLevel: 'low light', size: '2-4 Feet Tall', trait: 'Tolerant of low light, requires minimal watering, upright sword-shaped leaves.' },

    { plantName: 'Peace Lily (Spathiphyllum spp.)', description: 'Peace lilies are sturdy, easy to grow plants with glossy, dark green oval leaves that narrow to a point. The leaves rise directly from the soil. These plants also periodically produce lightly fragrant white flowers that resemble calla lilies. The long-lasting, pure white flowers will turn a pale green as they age.', image: '', careLevel: 'Beginner to Intermediate', waterLevel: 'Regular Water', lightLevel: 'Indirect Light', size: '1-4 Feet Tall', trait: 'Enjoys indirect light elegant white blooms, indicates when it needs water.' },

    { plantName: 'ZZ Plant (Zamioculcas zamiifolia)', description: 'Zamioculcas zamiifolia, commonly called ZZ plant or aroid palm, is an aroid family member that is native to dry grassland and forest in Eastern Africa. It is a stemless evergreen plant that typically grows to 3Ft tall with attractive, pinnately compound leaves rising up from its rhizomes.', image: '', careLevel: 'Beginner', waterLevel: 'Regular Watering', lightLevel: 'Indirect light', size: '2-3 Ft', trait: 'Low light-tolerant, glossy, dark green leaves, drought-resistant.' },

    { plantName: 'Spider Plant (Chlorophytum comosum)', description: 'The plant has triangular, fleshy leaves with serrated edges, yellow tubular flowers and fruits that contain numerous seeds. Each leaf is composed of three layers: 1st An inner clear gel that contains 99% water and rest is made of glucomannans, amino acids, lipids, sterols and vitamins.', image: '', careLevel: 'Beginner', waterLevel: 'Minimal Water', lightLevel: 'Bright Light', size: 'Up to 1Ft', trait: 'Adaptable to various conditions, produces arching stems with baby spiderettes.' },

    { plantName: 'Rubber Plant (Ficus elastica)', description: 'In colder climates, this is an extremely popular houseplant that typically grows to 2-10 tall. It is noted for its thick, leathery, glossy, dark green leaves (to 12” long and 5” wide) and pink to purplish stipules. Milky sap from these trees was used to make an inferior rubber in the early 1900s.', image: '', careLevel: 'Beginner to Intermediate', waterLevel: 'moderate watering', lightLevel: 'Bright, indirect light', size: '2-6 Ft', trait: 'Tolerates low light, large, glossy leaves, benefits from occasional pruning.' },

    { plantName: 'Pothos (Epipremnum aureum)', description: 'Epipremnum aureum is a species in the arum family Araceae, native to Mo-orea in the Society Islands of French Polynesia.an evergreen vine growing to 20 m (66 ft) tall, with stems up to 4 cm (2 in) in diameter.', image: '', careLevel: 'BEginner', waterLevel: 'moderate watering', lightLevel: 'Low to bright light', size: 'Varies', trait: 'Thrives in low light, trailing vines with heart-shaped leaves.' },

    { plantName: 'Fiddle Leaf Fig (Ficus lyrata)', description: 'he fiddle-leaf fig is a small tropical tree and broadleaf evergreen, commonly grown and popular as a houseplant in many areas of the United States. As a houseplant, it will grow 2 to 10 feet tall. It has large, broad, lyre-shaped, green leaves that can measure up to 18 inches long.', image: '', careLevel: 'Intermediate', waterLevel: 'regular watering', lightLevel: 'Bright, indirect light', size: '5-10 Ft', trait: 'Prefers bright, indirect light, large, violin-shaped leaves.' },

    { plantName: 'Jade Plant (Crassula ovata)', description: 'The jade plant is an evergreen with thick branches. It has thick, shiny, smooth leaves that grow in opposing pairs along the branches. Leaves are a rich jade green, although some may appear to be more of a yellow-green.', image: '', careLevel: 'Beginner', waterLevel: 'infrequent watering', lightLevel: 'Bright light', size: '1-3 Ft', trait: 'Drought-tolerant, fleshy green leaves, symbolic of prosperity.'},

    { plantName: 'Chinese Money Plant (Pilea peperomioides)', description: 'Pilea peperomioides is an erect, evergreen perennial plant, with shiny, dark green, circular leaves up to 10 cm (4 in) in diameter on long petioles. The leaves are described as peltate—circular, with the petiole attached near the centre. The plant is completely hairless.', image: '', careLevel: 'Beginner', waterLevel: 'Moderate watering', lightLevel: 'Indirect Lighting', size: '8-12 inches', trait: 'Circular leaves on upright stems, easy to propagate.' },

    { plantName: 'Monstera Deliciosa', description: 'Monstera deliciosa is mainly cultivated for its large, glossy, dark green leaves that can reach up to one metre in length. The edges of the juvenile leaves are unbroken, but as the plant matures the leaf edges become deeply cut and have elliptic holes in them.', image: '', careLevel: 'Beginner to Intermediate', waterLevel: 'Regular Watering', lightLevel: 'Indirect Light', size: '2-4 Ft', trait: 'Adapts to various light levels, iconic split leaves.' },

    { plantName: 'Parlor Palm (Chamaedorea elegans)', description: 'Handsome, arching, green pinnate leaves, with 12 or more pairs of narrow leaflets per leaf, lend a tropical flair to indoor locations. Clusters of yellow flowers in loose spirals may bloom in spring if enough light is present. Plants are dioecious. Black fruit is attractive when it appears.', image: '', careLevel: 'Beginner', waterLevel: 'Regular Watering', lightLevel: 'Indirect lighting', size: '2-4 Ft', trait: 'Adapts to low light, feathery fronds, compact size.'},

    { plantName: 'Calathea (Calathea spp.)', description: 'Calathea plants are part of the family of plants known as Marantaceae, which is a species of flowering plants from tropical areas such as Africa. They are famous for their wide, green, colorful leaves. These wide leaves make them popular for areas of low light.', image: '', careLevel: 'Intermediate', waterLevel: 'Regular Watering', lightLevel: 'low level indirect lighting', size: 'varies', trait: 'Requires high humidity, ornate, patterned leaves, sensitive to direct sunlight.'},

    { plantName: 'Bird of Paradise (Strelitzia reginae)', description: 'Emerging from a horizontal green and pink beak-like spathe, brilliant orange and vivid blue flowers bloom in succession, resembling the crest on a birds head. Individual flowers last for about a week, but the spathe holds 5 to 7 flowers, guaranteeing a long-lasting display.', image: 'Intermediate', careLevel: '', waterLevel: 'Regular Watering', lightLevel: 'Indirect Light', size: '6 Ft', trait: 'Banana-like leaves, prefers bright, indirect light.'},

    { plantName: 'Pilea Moon Valley (Pilea involucrata)', description: 'The Moon Valley Pilea or Pilea Mollis is native to Central and South America. Its common name, Moon Valley Pilea, is inspired by its deeply dimpled leaves – thought to look like the craters and valleys on the moon. The leaves are bushy in nature and are typically a bright yellow-green with dark copper veins.', image: '', careLevel: '', waterLevel: 'Regular Watering', lightLevel: 'Bright Indirect Lighting', size: '6-12 inches', trait: ''},

    { plantName: 'Boston Fern (Nephrolepis exaltata)', description: 'Nephrolepis exaltata has broad fronds with alternate leaflets (pinnae) on either side of the midrib. The pale- to medium-green fronds can grow up to 4 feet long and 6 inches wide.', image: '', careLevel: 'Intermediate', waterLevel: 'Regular Watering', lightLevel: 'Indirect Lighting', size: '1-3 Ft', trait: 'High humidity lover, delicate, arching fronds.'},

    { plantName: 'Hoya Carnosa (Hoya carnosa)', description: 'Plants feature glossy, elliptic, fleshy, dark green leaves (to 4” long) and tight rounded clusters (umbels) of fragrant white summer flowers. Each tiny flower (to 1/2” diameter) sports a distinctive, star-shaped, red-centered corona. Each cluster may include from 10-30 flowers.', image: '', careLevel: 'Beginner to Intermediate', waterLevel: 'Infrequent Watering', lightLevel: 'Bright Indierct Lighting', size: '', trait: 'Waxy, trailing vines, produces clusters of fragrant flowers.'},

    { plantName: 'Dieffenbachia (Dieffenbachia spp.)', description: 'Dieffenbachia is a genus of tropical perennials with several species that are commonly grown as houseplants. They feature pointed, ovate leaves in a variety of combinations of green, cream, and white colors.', image: '', careLevel: 'Beginner', waterLevel: 'Regular Watering', lightLevel: 'Medium To low light', size: '1-6 Ft', trait: 'Bold, variegated leaves, thrives in low to moderate light.' },

    { plantName: 'African Violet (Saintpaulia spp.)', description: 'The members of Saintpaulia are small perennial herbs with thick, hairy, ovate leaves. These dark green leaves have long petioles (leaf stems) and are arranged in a basal cluster at the base of the plant. The violet-like flowers are bilaterally symmetric with five petals and can be violet, white, or pink in colour.', image: '', careLevel: 'Intermediate', waterLevel: 'consistent watering', lightLevel: 'Indirect light', size: '', trait: 'Vibrant, velvety flowers, prefers bright, indirect light.'},

    { plantName: 'Schefflera (Schefflera arboricola)', description: 'Schefflera arboricola, commonly called umbrella plant or dwarf schefflera, is an evergreen shrub or small tree that grows in tropical climates to 10-25 tall. It is native to Taiwan. In the wild, it sometimes grows on other trees as an epiphyte.', image: '', careLevel: 'Beginner', waterLevel: 'moderate watering', lightLevel: 'Bright, indirect light', size: '3-6 Ft', trait: 'Waxy, trailing vines, produces clusters of fragrant flowers.' },

    { plantName: 'Lucky Bamboo (Dracaena sanderiana)', description: 'racaena sanderiana, commonly called lucky bamboo, is a small to medium sized, slow-growing, herbaceous perennial native to tropical western Africa. Mature plants will reach up to 5 tall with an equal spread. The slim, upright stems have distinct nodes giving them a bamboo-like appearance.', image: '', careLevel: 'Beginner', waterLevel: 'Regular Watering', lightLevel: 'Indirect Light', size: 'Varies', trait: 'Grows in water or soil, often used in arrangements, symbolic of good luck.'},

    { plantName: 'Nerve Plant (Fittonia spp.)', description: 'Normally grown as a potted houseplant, nerve plant (Fittonia spp.) is a spreading evergreen perennial with delicately veined, deep-green, ovate leaves. Although the most popular vein color is silvery-white, you can also readily find varieties with veins in red, pink, white, and green.', image: '', careLevel: 'Beginner to Intermediate', waterLevel: 'regular watering', lightLevel: 'indirect light', size: '', trait: 'Thrives in bright, indirect light but avoid direct sunlight.Pruning can help maintain a bushy appearance. Non-toxic to pets.'},

    { plantName: 'Christmas Cactus (Schlumbergera spp.)', description: 'It is native to Brazil and is technically an epiphyte that grows in humid rainforests—a very different habitat from the "typical" cacti of Mexico and the Desert Southwest. It has fleshy stems and showy flowers and grows well as a houseplant, preferring moisture but adapting to a variety of home environments.', image: '', careLevel: 'well-draining soil', waterLevel: 'regular watering', lightLevel: 'Indirect light', size: '', trait: ''},

    { plantName: 'Croton (Codiaeum variegatum)', description: 'Croton is a small shrub used as a landscape plant in tropical climates. In its native habitat, croton is a branching, bushy shrub that grows up to 10 feet tall but those offered as houseplants are usually much smaller than the wild plant. The large, thick, leathery leaves are 2 to 12 inches long and quite variable.', image: '', careLevel: '', waterLevel: 'regular watering', lightLevel: 'Bright, indirect light', size: '2-6 Ft', trait: ''},

    { plantName: 'Air Plant (Tillandsia spp.)', description: 'Air plants get their common name from the fact that they get all of their nutrients from the atmosphere. Most species of Tillandsia have thin, stiff leaves covered in scales, often giving them a fuzzy, gray-green appearance. They have small flowers, usually less than two inches in size.', image: '', careLevel: 'Beginner to Intermediate', waterLevel: 'soak in water every 1-2 weeks', lightLevel: 'Bright, indirect light', size: 'varies', trait: 'Epiphytic, no soil needed, absorbs nutrients through leaves.'},
];

module.exports = { plants }